### PR TITLE
Traefik reverse proxy with Authelia SSO on Docker

### PR DESCRIPTION
**Pull request by arevindh**
Single reverse proxying solution for a home lab using Traefik and Authelia on Docker standalone .
Tested working on Raspberry Pi 4 4GB

### CODE REVIEW

**Comment by kunalgrover05** [comment]
Looks really good! Lots of amazing information.

Nitpicks on some of the documentation
- Reminder to not use any copyright images. Please recheck that all images are correctly attributed before use.
- Check the title heading levels. eg: What is Traefik? -> What does it do? are cohesive but maybe should not be at the same level? This becomes helpful when your doc grows and you want to add TOC.
- On that note, this is good case for adding TOC, would you like to try? https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/#in-page-navigation-with-table-of-contents
Maybe we should enforce it everywhere too
- Small typo: "Installtion"

I don't have the expertise to verify that all steps are done, but I think you are the expert here so I am good to merge this.

**Comment by arevindh** [comment]
> Looks really good! Lots of amazing information.
> 
> Nitpicks on some of the documentation
> 
>     * Reminder to not use any copyright images. Please recheck that all images are correctly attributed before use.
> 
>     * Check the title heading levels. eg: What is Traefik? -> What does it do? are cohesive but maybe should not be at the same level? This becomes helpful when your doc grows and you want to add TOC.
> 
>     * On that note, this is good case for adding TOC, would you like to try? https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/#in-page-navigation-with-table-of-contents
>       Maybe we should enforce it everywhere too
> 
>     * Small typo: "Installtion"
> 
> 
> I don't have the expertise to verify that all steps are done, but I think you are the expert here so I am good to merge this.

Doc is in progress , will correct the headings . So this one does not support auto TOC , will do it.

**Comment by kunalgrover05** [comment]
Looks really good, adding a couple of questions (non blocking), these can be answered in later PR too. 

1- Does the placement of this content under Docker seem correct? It doesn't help you work / monitor docker in any way but we use Docker to set it up. That might be true for everything else but putting everything under docker may be confusing. If I understood the intent correctly, this is for building remote access. Should we put this under HA -> Remote Access or just under Remote access?
2- Do you think we could add one line on each of "why would a newbie require this?". I think I understood the point but not from the context of a home user from your doc. Maybe just add a "Why?" section to introduce why should people set it up?

**Comment by arevindh** [comment]
> building remote access

1. It can be used for remote access, the best use case is for a centralized domain, SSL, and Auth for local access. It does help to organize HTTP services hosted on docker and does utilize features specific to docker.
2. Updated doc

**Comment by kunalgrover05** [comment]
Thanks for adding the why section.

I'm approving this but I'd still appreciate thinking about a better placement. Maybe just a section called infrastructure or network?

**Review by kunalgrover05 — APPROVED** [review]

**Comment by kunalgrover05** [comment]
Merging before breaking changes, can continue organization discussion later.

**Pull request merged**
